function [ A_out, t_out, r_out ] = BiRed( A, t, r )

  function [ rho, ...
             u2, tau ] = Housev( chi1, ...
                                 x2 )

    normx = sqrt(chi1 * chi1 + x2' * x2);

    rho = - sign(chi1) * normx;
    nu1 = chi1 - rho;
    u2 = x2 / nu1;

    tau = (1 + u2' * u2) / 2;

    return
  end

  function [ u, tau ] = Housev1( x )

    n = size(x, 1);
  
    [ rho, ...
       u2, tau ] = Housev( x(1,1), ...
                           x(2:n,1) );
                     
    u = [ rho
           u2 ];
  end
 
  [ ATL, ATR, ...
    ABL, ABR ] = FLA_Part_2x2( A, ...
                               0, 0, 'FLA_TL' );

  [ tT, ...
    tB ] = FLA_Part_2x1( t, ...
                         0, 'FLA_TOP' );

  [ rT, ...
    rB ] = FLA_Part_2x1( r, ...
                         0, 'FLA_TOP' );
  
  while ( size( ATL, 1 ) < size( A, 1 ) )
    [ A00,  a01,     A02,  ...
      a10t, alpha11, a12t, ...
      A20,  a21,     A22 ] = FLA_Repart_2x2_to_3x3( ATL, ATR, ...
                                                    ABL, ABR, ...
                                                    1, 1, 'FLA_BR' );

    [ t0, ...
      tau1, ...
      t2 ] = FLA_Repart_2x1_to_3x1( tT, ...
                                    tB, ...
                                    1, 'FLA_BOTTOM' );

    [ r0, ...
      rho1, ...
      r2 ] = FLA_Repart_2x1_to_3x1( rT, ...
                                    rB, ...
                                    1, 'FLA_BOTTOM' );
    %------------------------------------------------------------%
    [ alpha11, ...
      a21, tau1 ] = Housev( alpha11, ...
                              a21 );
    % Apply H to the left
    w12t = (a12t + a21' * A22) / tau1;
    a12t = a12t - w12t;
    A22  = A22 - a21 * w12t;

    % No need to zero out the row if there's nothing to zero out
    if (~isempty(a12t))
      [ u12, rho1 ] = Housev1(a12t');
      % Apply H to the right
      a12t = u12';
      u12(1) = 1;
      x12 = A22 * u12;
      A22 = A22 - (x12 * u12') / rho1;
    end

    %------------------------------------------------------------%
    [ ATL, ATR, ...
      ABL, ABR ] = FLA_Cont_with_3x3_to_2x2( A00,  a01,     A02,  ...
                                             a10t, alpha11, a12t, ...
                                             A20,  a21,     A22, ...
                                             'FLA_TL' );

    [ tT, ...
      tB ] = FLA_Cont_with_3x1_to_2x1( t0, ...
                                       tau1, ...
                                       t2, ...
                                       'FLA_TOP' );

    [ rT, ...
      rB ] = FLA_Cont_with_3x1_to_2x1( r0, ...
                                       rho1, ...
                                       r2, ...
                                       'FLA_TOP' );                                             
  end

  A_out = [ ATL, ATR
            ABL, ABR ];

  t_out = [ tT
            tB ];
        
  r_out = [ rT
            rB ];

return
end